version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: wc_redis
    ports: ["6379:6379"]
    networks: [wcnet]

  server_alpha:
    image: ads:lab
    container_name: wc_server_alpha
    working_dir: /app/server
    volumes:
      - ./server:/app/server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TEXT_DIR=/app/server/texts
      - SERVER_HOST=wc_server_alpha
      - SERVER_PORT=18861
    command: >
      bash -lc "pip3 install --no-cache-dir redis &&
                python server.py"
    depends_on: [redis]
    networks: [wcnet]

  client_alpha:
    image: ads:lab
    container_name: wc_client_alpha
    working_dir: /app/client
    volumes:
      - ./client:/app/client
      - ./client:/out
    environment:
      - SERVER_HOST=wc_server_alpha
      - SERVER_PORT=18861
      - NAME=alpha
    command: >
      bash -lc "python -u client.py"
    depends_on: [server_alpha]
    networks: [wcnet]

  client_beta:
    image: ads:lab
    container_name: wc_client_beta
    working_dir: /app/client
    volumes:
      - ./client:/app/client
      - ./client:/out
    environment:
      - SERVER_HOST=wc_server_alpha
      - SERVER_PORT=18861
      - NAME=beta
    command: >
      bash -lc "python -u client.py"
    depends_on: [server_alpha]
    networks: [wcnet]

  client_gamma:
    image: ads:lab
    container_name: wc_client_gamma
    working_dir: /app/client
    volumes:
      - ./client:/app/client
      - ./client:/out
    environment:
      - SERVER_HOST=wc_server_alpha
      - SERVER_PORT=18861
      - NAME=gamma
    command: >
      bash -lc "python -u client.py"
    depends_on: [server_alpha]
    networks: [wcnet]

  client_delta:
    image: ads:lab
    container_name: wc_client_delta
    working_dir: /app/client
    volumes:
      - ./client:/app/client
      - ./client:/out
    environment:
      - SERVER_HOST=wc_server_alpha
      - SERVER_PORT=18861
      - NAME=delta
    command: >
      bash -lc "python -u client.py"
    depends_on: [server_alpha]
    networks: [wcnet]

  client_epsilon:
    image: ads:lab
    container_name: wc_client_epsilon
    working_dir: /app/client
    volumes:
      - ./client:/app/client
      - ./client:/out
    environment:
      - SERVER_HOST=wc_server_alpha
      - SERVER_PORT=18861
      - NAME=epsilon
    command: >
      bash -lc "python -u client.py"
    depends_on: [server_alpha]
    networks: [wcnet]

networks:
  wcnet:
    driver: bridge
